const Address_DATA = [
  {
    _id: "1",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "2",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "3",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "4",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "5",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "6",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  {
    _id: "7",
    name: "sayanthan",
    Province: "Northern",
    districts: "jaffna",
    contactnumber: "2372872832",
    default: "default",
  },
  // {
  //   _id: "8",
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   _id: "9",
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
  // {
  //   name: "sayanthan",
  //   Province: "Northern",
  //   districts: "jaffna",
  //   contactnumber: "2372872832",
  //   default: "default",
  // },
];

export { Address_DATA };
